/*
 * motor.c
 *
 *  Created on: 13 set 2026
 *      Author: vito
 */

//FUNZIONE PER AZIONARE MOTORE
//FUNZIONE PER FERMARE MOTORE
//FUNZIONE PER SETTARE VELOCITA MOTORE
//FUNZIONE PER SETTARE SPOSTAMENTO
